name: Build LaTeX document

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

permissions:
  contents: write
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: proof-theory.tex
#      - name: Upload PDF file
#        uses: actions/upload-artifact@v3
#        with:
#          name: PDF
#          path: proof-theory.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: proof-theory.pdf
      
