name: Build and release

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag including hierarchical tags like v1.0/beta
  
jobs:
  build_latex:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: proof-theory.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: proof-theory.pdf
      
